### ISSUE TITLE
GPG signature for this Yarn release is invalid?

### ISSUE THREAD

**Issue by dolebas** [lukeed/preact-starter#20]
Was curious about the demo but the preact-starter.now.sh link seems to be broken. Tried deploying a clean fork to Netlify with build/dist but got this error:
![image](https://user-images.githubusercontent.com/27515901/32892043-3b8f169a-cad5-11e7-9e2c-5eb2f2b0e22e.png)

**Comment by lukeed** [comment]
Ah interesting. Thanks! I'll regenerate now~

**Comment by lukeed** [comment]
Also republished the Now demo: https://preact-starter.now.sh/

**Comment by dolebas** [comment]
Great, looks good!
